spring.application.name=board
server.port=8080

# MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/board
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.human.board.vo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Thymeleaf
spring.thymeleaf.cache=false

# File Upload
upload.path=C:/uploads
